@startuml MDD
skinparam style strictuml
skinparam ArrowThickness 2
skinparam ArrowColor #gray
hide empty members
title Modèle du domaine (adapté pour l'Université)

class Universite <<Organisation>> {
  nom : String
  adresse : String
  
}
class Etudiant <<Role>> {
  matricule : String
  nom : String
  prenom : String  
}
class Cours <<Description d'entité>> {
  nom : String
  sigle : String
  prealable : Cours[ ]
}
class Inscription << Transaction >> {
  
  
}
class GroupeCours <<Conteneur>> {
  groupe : int
  listCours : Cours[ ]  
}
class Trimestre <<Catalogue, Conteneur>> {
  saison : String
  dateDebut : Date
  dateFin : Date
}
class AgentAdministratif <<Rôle>> {
  nom : String
  matricule : String
}
class Horaire <<Document administratif>> {
  dateSession : String[ ][ ]
}

' associations
Universite -- "1..*" Etudiant : offre-des-services-à  >
Universite "1" -- "0..*" Cours : Offre-des >
Cours -- "0..*" Cours : est-prealable >
Etudiant "1" -- "0..*" Inscription : fait >
GroupeCours "1" -- "0..*" Cours : regroupe-des >
GroupeCours "0..*" -- "1" Trimestre : affiche-des >
AgentAdministratif "1" -- "0..*" Trimestre : planifie >
Inscription "1" -- "1" Trimestre : selectionne-prochain >
Inscription "1" -- "1" Horaire : genere >
@enduml









